<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bermuda | PHP Framework</title>
    <link rel="icon" href="favicon.png" type="image/png" />
    <link href="https://fonts.googleapis.com/css?family=Reem+Kufi|Roboto:300" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="css/themes/yellow-black.css">
</head>
<body>
<main style="background-color:#ffeb00;">
    <div class="intro">Hello, I'm <span style="background-color: #1e1e1e; border-radius: 14px; color: #ffffff">Bermuda!</span></div>
    <div class="tagline"><span style="background-color: #ffffff ;padding-left: 5%;padding-right: 5%;font-family: 'Reem Kufi', sans-serif;font-weight: 600;color: #000000;">Psr-compatible PHP Micro Framework</span></div>
    <div class="icons-social">
        <a target="_blank" href="https://github.com/bermudaphp"><i class="fab fa-github-square"></i></a>
    </div>
</main>
</body>
</html>
